const types = {
  PRODUCT_SHOW: "PRODUCT_SHOW",
  PRODUCT_ADD_TO_CART: "PRODUCT_ADD_TO_CART",
  PRODUCT_REMOVE_FROM_CART: "PRODUCT_REMOVE_FROM_CART",
  PRODUCT_REMOVE_ONE_FROM_CART: "PRODUCT_REMOVE_ONE_FROM_CART",
};

export default types;
